# Spark Default Configuration for Hadoop HDFS / YARN Cluster
spark.master                     yarn
spark.submit.deployMode          client
spark.app.name                   NasaLogAnalyticsPipeline
spark.driver.memory              16g
spark.executor.instances         3
spark.executor.memory            27g
spark.executor.memoryOverhead    2764m
spark.executor.cores             5
spark.sql.adaptive.enabled       true
spark.sql.adaptive.coalescePartitions.enabled true
spark.sql.shuffle.partitions     45
spark.default.parallelism        30
spark.serializer                 org.apache.spark.serializer.KryoSerializer
spark.eventLog.enabled           true
spark.eventLog.dir               hdfs://namenode:9000/spark-logs
spark.history.fs.logDirectory    hdfs://namenode:9000/spark-logs
spark.sql.parquet.compression.codec snappy
